"""add subscription_gate_text to settings

Revision ID: 03d6c1c759e7
Revises: 573da2f99851
Create Date: 2026-09-16 13:33:41.117977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d6c1c759e7'
down_revision: Union[str, None] = '573da2f99851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('subscription_gate_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'subscription_gate_text')
    # ### end Alembic commands ###
