"""add web login tokens and sessions

Revision ID: 3ebd49e0a22e
Revises: 9f493b5cf562
Create Date: 2026-09-22 08:53:17.299539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebd49e0a22e'
down_revision: Union[str, None] = '9f493b5cf562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_login_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_login_tokens_token_hash'), 'web_login_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_web_login_tokens_user_id'), 'web_login_tokens', ['user_id'], unique=False)
    op.create_table('web_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_sessions_token_hash'), 'web_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_web_sessions_user_id'), 'web_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_sessions_user_id'), table_name='web_sessions')
    op.drop_index(op.f('ix_web_sessions_token_hash'), table_name='web_sessions')
    op.drop_table('web_sessions')
    op.drop_index(op.f('ix_web_login_tokens_user_id'), table_name='web_login_tokens')
    op.drop_index(op.f('ix_web_login_tokens_token_hash'), table_name='web_login_tokens')
    op.drop_table('web_login_tokens')
    # ### end Alembic commands ###
