"""add share_text to settings

Revision ID: 573da2f99851
Revises: 5f7ae4d11288
Create Date: 2026-09-16 07:26:53.885333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573da2f99851'
down_revision: Union[str, None] = '5f7ae4d11288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('share_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'share_text')
    # ### end Alembic commands ###
