"""add marra2 campaigns, participants, daily progress

Revision ID: 9f493b5cf562
Revises: f2b7c8d4a1e9
Create Date: 2026-09-22 08:35:51.228539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f493b5cf562'
down_revision: Union[str, None] = 'f2b7c8d4a1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marra_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prize_text', sa.String(length=500), nullable=True),
    sa.Column('book_title', sa.String(length=255), nullable=False),
    sa.Column('book_cover_file_id', sa.String(length=255), nullable=True),
    sa.Column('book_text', sa.Text(), nullable=False),
    sa.Column('day_count', sa.Integer(), nullable=False),
    sa.Column('daily_minutes_required', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marra_campaigns_is_active'), 'marra_campaigns', ['is_active'], unique=False)
    op.create_table('marra_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_eliminated', sa.Boolean(), nullable=False),
    sa.Column('eliminated_on_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['marra_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_marra_participant')
    )
    op.create_index(op.f('ix_marra_participants_campaign_id'), 'marra_participants', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_marra_participants_is_eliminated'), 'marra_participants', ['is_eliminated'], unique=False)
    op.create_index(op.f('ix_marra_participants_user_id'), 'marra_participants', ['user_id'], unique=False)
    op.create_table('marra_daily_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('seconds_read', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['marra_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'day_number', name='uq_marra_daily_progress')
    )
    op.create_index(op.f('ix_marra_daily_progress_participant_id'), 'marra_daily_progress', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marra_daily_progress_participant_id'), table_name='marra_daily_progress')
    op.drop_table('marra_daily_progress')
    op.drop_index(op.f('ix_marra_participants_user_id'), table_name='marra_participants')
    op.drop_index(op.f('ix_marra_participants_is_eliminated'), table_name='marra_participants')
    op.drop_index(op.f('ix_marra_participants_campaign_id'), table_name='marra_participants')
    op.drop_table('marra_participants')
    op.drop_index(op.f('ix_marra_campaigns_is_active'), table_name='marra_campaigns')
    op.drop_table('marra_campaigns')
    # ### end Alembic commands ###
